### ISSUE TITLE
How implement same model with node http end point

### ISSUE THREAD

**Issue by SantoshSKhavekar** [mderazon/node-deeplink#12]
I have created one http server and listening on port 2000.My deeplink is http://host:2000/deep?url=fb
 Now My server is handling request as
``` js
var http = require('http'); 
var deeplink = require('node-deeplink');
http.createServer(handleRequest).listen(2000);
function handleRequest(request, response){
    try {
        //log the request on console
        console.log(request.url);
       if(request.url=="/deep"){
		    console.log("deeplink:-   "+deeplink);
			deeplink({ 	
				fallback: 'https://na.nofer.com',
				android_package_name: 'com.na.nofer'	
			});

	   }
    } catch(err) {
        console.log(err);
    }
}
```
app is not installed in my android device .once i have requested in android browser ,request is landing but it is not directing to nieghter fallback nor app store.
Can some one suggest on same.

**Comment by mderazon** [comment]
This module is **express** middleware / endpoint, take a look at the [example](https://github.com/mderazon/node-deeplink#example)

Need to do something like this
``` js
var express = require('express')
var deeplink = require('node-deeplink')

var app = express()

app.get('/deeplink', deeplink({ 
    fallback: 'https://na.nofer.com',
    android_package_name: 'com.na.nofer'
}))

// ... rest of the app
```

**Comment by SantoshSKhavekar** [comment]
Ya you are correct mderazon.I have used express endpoint and it is working fine .Just I wanted to know that is it possible to create http endpoint to redirect to Deeplink?

**Comment by mderazon** [comment]
The example above does just that, it creates http endpoint at `/deep` and it should redirect your android app to the deeplink

**Comment by SantoshSKhavekar** [comment]
Okay but the above example which you told in previous comment that is Express modue i.e Express server not Http module i.e Http server.Just I have to do by creating Http server and need to handle request for /deep.

**Comment by SantoshSKhavekar** [comment]
If I run this 
```
var express = require('express')
var deeplink = require('node-deeplink')

var app = express()

app.get('/deep', deeplink({ 
    fallback: 'https://na.nofer.com',
    android_package_name: 'com.na.nofer'
}))
```
it is working.

**Comment by mderazon** [comment]
So you mean that you don't want to use Express ?
Right now this module supports express, but it shouldn't be too hard to fork this and adjust it to work without express to fit your needs

**Comment by SantoshSKhavekar** [comment]
Yes mderazon ,as my requirement I have to do with http module.So I have tried it with all possible ways to work using http module ,unfortunatelly it didnot work.Now there is no another way for me ,I must use express module only as you told.
Anyway Thank you So much for your answers,
