### ISSUE TITLE
Struggling to get simple case working

### ISSUE THREAD

**Issue by booboothefool** [mderazon/node-deeplink#13]
I am trying to do "Connect Instagram" in my React Native iOS app. Instagram API doesn't allow URL schemes as valid redirect_uri's, so I assume I need to redirect to my server first, then use this library to redirect back to my app. 

First I set up the URL scheme in xcode as: `myapp`

Then I am able to hit: `myapp://`

In Instagram Manage API, I set the redirect_uri to: `https://myserver.com/linkinstagram?url=myapp%3A%2F%2F`

My server has:
```
app.get('/linkinstagram', deeplink({
  fallback: 'https://myfallback.com'
}));
```

However hitting `https://myserver.com/linkinstagram?url=myapp%3A%2F%2F` ends up going to the fallback. I tried this in iOS simulator as well as on an actual device. Any suggestions?

**Comment by mderazon** [comment]
Not sure I follow, are you trying to open Instagram app directly from your React Native app ?
If so, what is the Instagram url you're trying to open ?
