### ISSUE TITLE
Can not make it work

### ISSUE THREAD

**Issue by panagorn** [mderazon/node-deeplink#14]
I get this message Cannot GET /deeplink

**Comment by mderazon** [comment]
I can try and help, but I will have to see your code

**Comment by panagorn** [comment]
This is the code in Manifest

            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data
                    android:host="xxxxx.app.goo.gl"
                    android:scheme="http"/>
                <data
                    android:host="xxxxx.app.goo.gl"
                    android:scheme="https"/>
                <data
                    android:host="example.com"
                    android:scheme="http"/>
                <data
                    android:host="example.com"
                    android:scheme="https"/>

            </intent-filter>

This is the code to share the link on fb

    ShareLinkContent content = new ShareLinkContent.Builder()
                .setImageUrl(Uri.parse("http://www.jqueryscript.net/images/Simplest-Responsive-jQuery-Image-Lightbox-Plugin-simple-lightbox.jpg"))
                .setContentUrl(Uri.parse("https://s92sv.app.goo.gl/HuKx"))
                .setContentTitle("Title")
                .setContentDescription("Description")
                .build();
        ShareButton btn = (ShareButton) findViewById(R.id.share);
        btn.setShareContent(content);

And listening for deep linking

    // Build GoogleApiClient with AppInvite API for receiving deep links
        mGoogleApiClient = new GoogleApiClient.Builder(this)
                .enableAutoManage(this, this)
                .addApi(AppInvite.API)
                .build();

        // Check if this app was launched from a deep link. Setting autoLaunchDeepLink to true
        // would automatically launch the deep link if one is found.
        boolean autoLaunchDeepLink = false;
        AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, this, autoLaunchDeepLink)
                .setResultCallback(
                        new ResultCallback<AppInviteInvitationResult>() {
                            @Override
                            public void onResult(@NonNull AppInviteInvitationResult result) {
                                if (result.getStatus().isSuccess()) {
                                    // Extract deep link from Intent
                                    Intent intent = result.getInvitationIntent();
                                    String deepLink = AppInviteReferral.getDeepLink(intent);

                                    // Handle the deep link. For example, open the linked
                                    // content, or apply promotional credit to the user's
                                    // account.

                                    // ...
                                } else {
                                    Log.d("Main", "getInvitation: no deep link found.");
                                }
                            }
                        });

**Comment by mderazon** [comment]
This code looks like Android,
This is a server side (Node) package.

**Comment by panagorn** [comment]
The issue was my local server
