### ISSUE TITLE
Better Android Intent url

### ISSUE THREAD

**Issue by arditdine** [mderazon/node-deeplink#17]
I'm trying access the url directly from google chrome on my phone and it just stays on a blank page. After some research, I found out that the problem is with android_intent it's missing S.browser_fallback_url parameter. here's the full var: 

var android_intent = 'intent://' + path + '#Intent;scheme=' + scheme + ';package=' + androidPackageName + ';S.browser_fallback_url=' + fallback + ';end;'

**Comment by mderazon** [comment]
Thanks @arditdine .
According to [this](https://paul.kinlan.me/deep-app-linking-on-android-and-chrome), it seems like the fallback url will take precedence over the play store opening via the package name. Can you confirm ?


See the diagram from that article:

![](https://paul.kinlan.me/images/intent-click.png)
