### ISSUE TITLE
not working with chrome & how the smart link work ?

### ISSUE THREAD

**Issue by dorman99** [mderazon/node-deeplink#20]
I just making some simple project with node-deeplink packatge. it work only when i open it with my phone browser (non-chrome) . but it keep throwing me to the application store, dispite of when i have the app, it should opening the app directly right ? or there is someting i missing with the 'smart' link ?

**Comment by omnathpp** [comment]
facing the same issue. Any updates on this?

**Comment by mderazon** [comment]
Can you describe steps to reproduce ?
I have tested it on my phone (Pixel + Chrome) and it is working fine.

Have you checked the example file?
https://github.com/mderazon/node-deeplink/blob/master/example/app.js

If you write a code sample, similar to the example app, I could help you debug it
