### ISSUE TITLE
Don't open playstore if app is not installed.

### ISSUE THREAD

**Issue by ianmuninio** [mderazon/node-deeplink#21]
I have different path rules that I can open App Store or not open.

If i want to open the App Store when my app is not installed to my phone, I just set the `ios_store_link`. But if I want to redirect to fallback url instead of opening the App Store, I omit the `ios_store_link`.

This is possible on ios but not on android.

**Comment by mderazon** [comment]
That is because on Android, the play store url is derived directly from the package name.
We could possibly add a new optional query param `skipStore` that will go to the fallback url (either in query or in settings) instead of the app store.
