### ISSUE TITLE
it doesn't work for me

### ISSUE THREAD

**Issue by despossivel** [mderazon/node-deeplink#30]
For some reason on android just nothing happens.

Only in fallback desktop browser is executed

Can anyone tell me what's going on?

**Comment by shikharsrivastava23** [comment]
@mderazon can you help please?

```
var express = require('express');
var deeplink = require('node-deeplink');
var app = express();

// mount deeplink middleware
app.get(
  '/deeplink',
  deeplink({
    fallback: 'https://fallbacklink',
  })
);

app.use(express.static('public'));

app.listen(port);
console.log('deeplink service listening on port 3000');
```


This is the code that I have. 
When I open this link on android, it always goes to the fallback option, instead of the deeplink. 
I have tried the deeplink by making an <a> tag, and that opens up the app as expected. 

Can you tell what I might be missing?

**Comment by despossivel** [comment]
@shikharsrivastava23 I found several problems myself to use this deeplink, and I found it very problematic. And I gave up using it.

But now I'm using Firebase's "Dynamic Links" which are Deeplinks, and very easy to use, and solved my problem.

https://firebase.google.com/docs/dynamic-links?authuser=0

**Comment by shikharsrivastava23** [comment]
@despossivel I am able to generate deep links for my app in the form myapp://category/42. 
What is the deep link url that is required in firebase dynamic link? Can you guide me through it?

**Comment by despossivel** [comment]
@shikharsrivastava23  I had also created a deeplink just like you, and when I saw firebase, it was much easier than I thought to adapt.

you just need to enter your firebase console first and create your dynamic link for your app

just follow here if it is RN that everything will be very clear to you

https://rnfirebase.io/dynamic-links/usage

**Comment by mderazon** [comment]
Thanks for pointing out Firebase dynamic links @despossivel, it does look great indeed.
A lot have change in the landscape of deeplinks over the years, Apple / iOS made breaking changes multiple times and some things became just impossible with only using Javascript.

I will update the README with the recommendation to consider Firebase's solution 👍🏼
