### ISSUE TITLE
How to send fallback in queryparams

### ISSUE THREAD

**Issue by n4nadeem** [mderazon/node-deeplink#35]
Fallback in query params is not working as expected
https://dev-api.monhapp.com/deeplink?url=app://account&fallback="www.google.com" this link redirect to "https://dev-api.monhapp.com/"www.google.com"
What should I send in fallback so that this will ridirect to  www.google.com

**Comment by nirmeshmashru** [comment]
@n4nadeem 

passing fallbank link like below will work

`&fallback=https//google.com`

**Comment by mderazon** [comment]
Also best to url encode the parameters

`https://www.google.com` --> `https%3A%2F%2Fwww.google.com`
