### ISSUE TITLE
could not open page alert pops for couple of milliseconds before app store is opened on IOS

### ISSUE THREAD

**Issue by mderazon** [mderazon/node-deeplink#4]
when the app is not installed and the deeplink is opened in safari, an alert opens up

![img_0113](https://cloud.githubusercontent.com/assets/717076/8637447/923202f8-289a-11e5-8d7b-0e7d7c251508.PNG)

**Comment by egg-** [comment]
I think that fixed in ea81b5cb9c234b55f432d1ee57e47502395efe32, Is that still reproduce?

**Comment by mderazon** [comment]
It does fix, just wanted to create an issue for that since I wasn't aware of it in the first place
