### ISSUE TITLE
Getting an alert dialog saying download faild

### ISSUE THREAD

**Issue by codebreaker01** [mderazon/node-deeplink#5]
<img width="373" alt="screen shot 2015-08-13 at 9 33 47 am" src="https://cloud.githubusercontent.com/assets/2875830/9255557/ff59b1ce-419e-11e5-9eab-5ac17c2fdfbe.png">

Hey, 

I am a newbie at node and javascript. If you could help me out here that would be great.

I am getting the attached dialog when I hit the deeplink url.

I have made a deeplink function in the core server middleware. Whenever the server hits http://localhost:3000/deeplink* the following gets executed. The url query parameter is encoded but still this issue persists.

```javascript
exports.deeplink = function(req, res, next) {
  var link = deeplink({
      fallback: 'http://' + req.headers.host,
      ios_store_link: 'https://itunes.apple.com/us/app/cups-unlimited-coffee/id556462755?mt=8&uo=4',
  });
  link(req, res, next);
};
```

**Comment by mderazon** [comment]
Is it only on IOS 9 ? Haven't tested it on this version yet, there might have been some changes in Safari.

Can you try running the code in an earlier version in the simulator ?

**Comment by codebreaker01** [comment]
Getting the same error on iOS 8.4 as well

**Comment by mderazon** [comment]
deeplink already exposes a middleware, so there's no need to save it to a var before and execute it.
try doing

```js
exports.deeplink = deeplink({
    fallback: 'http://' + req.headers.host,
    ios_store_link: 'https://itunes.apple.com/us/app/cups-unlimited-coffee/id556462755?mt=8&uo=4',
});
```

see example here
https://github.com/mderazon/node-deeplink/blob/master/example/app.js

**Comment by codebreaker01** [comment]
No luck with that either. Same error.

**Comment by codebreaker01** [comment]
Is there any way we can have a callback with the inline html and from the controller response, send the html to client?

**Comment by mderazon** [comment]
Can you show me the complete code of what you're trying to do ?

**Comment by codebreaker01** [comment]
I don't think the javascript is going to the mobile client. All I can see is standardError.html. in the Safari debugger.

I am using the mean js boilerplate code. After the reset password token validation, a function checks if the reset link was clicked by iPad or iPhone and redirects them to the mobile deeplink which makes a get request to the deeplinked URL in the core server route.

```javascript
function(err, user) {
    var userAgent = req.headers['user-agent'];
    if (userAgent !== null && (userAgent.indexOf('iPhone') > -1 || userAgent.indexOf('iPad') > -1) {
  		res.redirect('/deeplink?url=myapp%3A%2F%2Freset');
    } else {
      if (!user) {
  			return res.redirect('/#!/password/reset/invalid');
  		}
  		res.redirect('/#!/password/reset/' + req.params.token);
    }
```
In my core server routes, there is wildcard route for deeplinks.
```javascript
	// Deeplinking into apps
	app.route('/deeplink*').get(core.deeplink);
```
In the core server controller - 

```javascript
exports.deeplink = deeplink({
    fallback: 'http://localhost:3000',
    ios_store_link: 'https://itunes.apple.com/us/app/cups-unlimited-coffee/id556462755?mt=8&uo=4',
});
};
```

**Comment by mderazon** [comment]
If the page doesn't load then my guess is that something is wrong in the routing configuration. 

Try logging the request going right before the deeplink middleware
``` js
// Deeplinking into apps
app.route('/deeplink*').get(function(req, res, next) { 
  console.log('here') 
  next()
}, core.deeplink);
```

**Comment by codebreaker01** [comment]
I don't think its a routing issue since I an able debug via the node inspector and see that the flow actually goes to the deeplink library and the javascript data to be inlined is constructed. After the inline html piping with response, I don't see any response body being constructed.

**Comment by mderazon** [comment]
Can you post a complete sample code ?

**Comment by codebreaker01** [comment]
Just uploaded the repo. I am directly hitting the url from from iOS simulator after running the server.

https://github.com/codebreaker01/Deeplink

**Comment by mderazon** [comment]
the problem is the the MEAN server messes with the header type and sets it to `text/plain` instead of `text/html`

**Comment by mderazon** [comment]
try updating to v0.2.2 and see how it goes

**Comment by codebreaker01** [comment]
I updated the version. Now I am getting a different error.

![simulator screen shot aug 17 2015 9 24 55 pm](https://cloud.githubusercontent.com/assets/2875830/9322354/b7bc28de-4526-11e5-9ae0-632546e81ef2.png)

**Comment by mderazon** [comment]
Do you have an app that can open the deep link ? Or can you try and open it in a real device ?

I think that you can't open itunes on the simulator

**Comment by codebreaker01** [comment]
Deeplinking and fallback to itunes both  are working on a real device but deeplinking is not on simulator(though I have the app installed). Any reason why deeplinking isn't happening on simulator?

Btw, thanks for the prompt responses and getting this resolved. :+1:

**Comment by mderazon** [comment]
Hmm, weird. Not sure why it doesn't work in the simulator. The fallback to itunes probably can't work there but not sure why it's not opening the app
